variable "project_name" {
  description = "The name of the project"
  type        = string
}

variable "environment_name" {
  description = "The name of the environment"
  type        = string
}

variable "accounts" {
  description = "The list of accounts names to create IAM users"
  type        = set(string)
}

variable "tags" {
  description = "The tags to apply to the resources"
  type        = map(string)
}


variable "generated_hcl_file_path" {
  description = "The path to the generated HCL file, not generated by default"
  type        = string
  default     = null
}

# Bucket configuration
variable "key" {
  description = "The key to store the state"
  type        = string
  default     = "terraform.tfstate"
}

# Bucket encryption
variable "encrypt_backend" {
  description = "The flag to encrypt the state"
  type        = bool
  default     = false
}