name: 'Build and Push Docker Image'
description: 'Builds and pushes Docker image to ECR'

inputs:
    aws_region:
      description: 'AWS region for the ECR'
      required: true
    
    aws_access_key_id:
      description: 'AWS Access Key ID'
      required: true
      
    aws_secret_access_key:
      description: 'AWS Secret Access Key'
      required: true 

    ecr_url:
      description: 'ECR URL to push the Docker image'
      required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    - name: Build and push Docker image
      run: |
        chmod +x ./build-container.sh
        cp .env.dist .env
        ./build-container.sh \
          --registry-ecr ${{ inputs.ecr_url }} \
          --timestamp \
          --commit \
          --branch \
          --date \
          --push || exit 1
      shell: bash